# Generated by Django 3.2 on 2021-04-17 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_auto_20210412_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only letters and spaces allowed.')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='tel',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9 ]*$', 'Only Numbers allowed.')]),
        ),
    ]
