# Generated by Django 3.2 on 2021-07-05 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_auto_20210417_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Solo letras y espacios.')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='tel',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9 ]*$', 'Solo números permitidos.')]),
        ),
    ]
